import { RACE_MODES, DIFFICULTIES, normalizeRaceOptions } from './race-options.js';
import { getMedalTargets, nextChampionshipRace } from './race-career.js';
import { getTrack } from './track.js';
import { getVehicle } from './vehicles.js';
import { icon } from './icons.js';
const esc = v => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time = seconds => `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
export function raceSetupMarkup(preferences,career){const options=normalizeRaceOptions(preferences),next=nextChampionshipRace(career),targets=getMedalTargets(preferences.track,preferences.vehicle);return `<div class="hq-mode-options" role="group" aria-label="Race mode">${RACE_MODES.map((m,i)=>`<button type="button" data-race-mode="${m.id}" aria-pressed="${m.id===options.mode}"><span class="hq-option-icon">${icon(['flag','timer','trophy'][i])}</span><strong>${esc(m.label)}</strong><span>${esc(m.description)}</span></button>`).join('')}</div><div class="hq-difficulty"><label for="race-difficulty">Rival difficulty</label><select id="race-difficulty" ${options.mode==='time-attack'?'disabled':''}>${DIFFICULTIES.map(d=>`<option value="${d.id}" ${d.id===options.difficulty?'selected':''}>${d.label} — ${esc(d.description)}</option>`).join('')}</select><p>Car performance stays the same. Difficulty changes how quickly your opponents race.</p></div><div class="hq-medals"><h3>${icon('trophy')} CIRCUIT MEDAL TARGETS</h3><p>Finish three laps in ${esc(getVehicle(preferences.vehicle).name)} at ${esc(getTrack(preferences.track).name)}.</p><dl>${Object.entries(targets).map(([m,t])=>`<div><dt>${m.toUpperCase()}</dt><dd>${time(t)}</dd></div>`).join('')}</dl><p>Game targets based on the stock car. Upgrades help. Records are kept separately for each mode and difficulty.</p></div>${next?`<div class="hq-tour"><strong>YOUR TOUR IS WAITING</strong><p>Round ${next.round} of 3 · ${esc(getTrack(next.track).name)} · ${esc(getVehicle(next.vehicle).name)}</p><button id="resume-tour" type="button" class="button secondary">${icon('flag')} CONTINUE TOUR</button></div>`:''}`;}
export function careerResultMarkup(result,persisted){if(!result?.recorded)return '';const t=result.tour;return `<section class="hq-result-career"><h3>${icon('trophy')} ${result.medal==='none'?(result.improved?'A NEW BENCHMARK':'RUN RECORDED'):`${result.medal.toUpperCase()} CIRCUIT MEDAL`}</h3><p>${result.medal==='none'?'Beat the bronze target on your next run.':'Your medal and best time have been recorded for this car, circuit, mode and difficulty.'}</p>${t?`<div class="hq-tour-result"><strong>${result.tourCompleted?'TOUR COMPLETE':`TOUR · ${t.rounds.length} / 3 ROUNDS`}</strong><span>${t.points} POINTS · ${t.credits.toLocaleString()} CR EARNED</span><ol>${t.rounds.map(r=>`<li>${esc(getTrack(r.track).name)} <b>P${r.position} · +${r.credits} CR</b></li>`).join('')}</ol></div>`:''}${!persisted?'<p role="status">Career saved for this session only. Browser storage is unavailable.</p>':''}</section>`;}
